import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/_globals.scss";
import SmoothScroll from "@/components/animations/SmoothScroll";
import TopSlider from "@/components/common/TopSlider";
import { CartProvider } from "@/contexts/CartContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Hema Pickles",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartProvider>
          <TopSlider />
          <SmoothScroll />
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
