import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/_globals.scss";
import SmoothScroll from "@/components/animations/SmoothScroll";
import TopSlider from "@/components/common/TopSlider";
import { CartProvider } from "@/contexts/CartContext";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Hema Pickles",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-8MERP52H1H"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {\`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-8MERP52H1H');
          \`}
        </Script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartProvider>
          <TopSlider />
          <SmoothScroll />
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
